// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsFcJEH6Uv0eeiITTs7iTHv2Gc9-4GUMI',
    appId: '1:319414840187:web:7bbcadd0ca4b15c69fabde',
    messagingSenderId: '319414840187',
    projectId: 'nhbedding-af73a',
    authDomain: 'nhbedding-af73a.firebaseapp.com',
    storageBucket: 'nhbedding-af73a.appspot.com',
    measurementId: 'G-64YMC2N55B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDHJKfqRDTqCn9FKQS9pke4M-xVJQzLNg',
    appId: '1:319414840187:android:5f88765475ca49b39fabde',
    messagingSenderId: '319414840187',
    projectId: 'nhbedding-af73a',
    storageBucket: 'nhbedding-af73a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE8QC7_q31B4dblyf3mE4kohPvOEkq9No',
    appId: '1:319414840187:ios:90f4982dd2e568549fabde',
    messagingSenderId: '319414840187',
    projectId: 'nhbedding-af73a',
    storageBucket: 'nhbedding-af73a.appspot.com',
    androidClientId: '319414840187-0jhes3qhpb01nlkkjqo6hovbq8t3e1f3.apps.googleusercontent.com',
    iosClientId: '319414840187-g58vbsr3nthc5vepildiaulu8bda46se.apps.googleusercontent.com',
    iosBundleId: 'com.example.nhbedding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE8QC7_q31B4dblyf3mE4kohPvOEkq9No',
    appId: '1:319414840187:ios:90f4982dd2e568549fabde',
    messagingSenderId: '319414840187',
    projectId: 'nhbedding-af73a',
    storageBucket: 'nhbedding-af73a.appspot.com',
    androidClientId: '319414840187-0jhes3qhpb01nlkkjqo6hovbq8t3e1f3.apps.googleusercontent.com',
    iosClientId: '319414840187-g58vbsr3nthc5vepildiaulu8bda46se.apps.googleusercontent.com',
    iosBundleId: 'com.example.nhbedding',
  );
}
