// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxsAnPLtQPNR7axVXcWHeYeMiyTu-R0rs',
    appId: '1:764580115555:web:e879dd268427b60498f456',
    messagingSenderId: '764580115555',
    projectId: 'tiendienalias',
    authDomain: 'tiendienalias.firebaseapp.com',
    storageBucket: 'tiendienalias.appspot.com',
    measurementId: 'G-9YBW4GLMJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy-BQ7nFbspTsrJf0E_kqlxhctI1O_0A8',
    appId: '1:764580115555:android:330bd6dc9171f79498f456',
    messagingSenderId: '764580115555',
    projectId: 'tiendienalias',
    storageBucket: 'tiendienalias.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhu-AUyaLJu50h4HUYlSe_1q2hQ2U4pS4',
    appId: '1:764580115555:ios:2fb4ece1ea66d0f798f456',
    messagingSenderId: '764580115555',
    projectId: 'tiendienalias',
    storageBucket: 'tiendienalias.appspot.com',
    iosBundleId: 'com.example.tiendienAlias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhu-AUyaLJu50h4HUYlSe_1q2hQ2U4pS4',
    appId: '1:764580115555:ios:e0a0a68eb19cb08f98f456',
    messagingSenderId: '764580115555',
    projectId: 'tiendienalias',
    storageBucket: 'tiendienalias.appspot.com',
    iosBundleId: 'com.example.tiendienAlias.RunnerTests',
  );
}
